// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accesses                string
	AppointmentImages       string
	Appointments            string
	Auths                   string
	Codes                   string
	Designs                 string
	Follows                 string
	Images                  string
	Likes                   string
	Links                   string
	Payments                string
	Plans                   string
	PostImages              string
	Posts                   string
	Profiles                string
	Reviews                 string
	RolesUsers              string
	Sessions                string
	Shares                  string
	StudioAdminsPermissions string
	StudioUserHistories     string
	StudioUsers             string
	Studios                 string
	Subscriptions           string
	Tattoos                 string
	TokenPasswords          string
	Tokens                  string
	Users                   string
	Views                   string
}{
	Accesses:                "accesses",
	AppointmentImages:       "appointment_images",
	Appointments:            "appointments",
	Auths:                   "auths",
	Codes:                   "codes",
	Designs:                 "designs",
	Follows:                 "follows",
	Images:                  "images",
	Likes:                   "likes",
	Links:                   "links",
	Payments:                "payments",
	Plans:                   "plans",
	PostImages:              "post_images",
	Posts:                   "posts",
	Profiles:                "profiles",
	Reviews:                 "reviews",
	RolesUsers:              "roles_users",
	Sessions:                "sessions",
	Shares:                  "shares",
	StudioAdminsPermissions: "studio_admins_permissions",
	StudioUserHistories:     "studio_user_histories",
	StudioUsers:             "studio_users",
	Studios:                 "studios",
	Subscriptions:           "subscriptions",
	Tattoos:                 "tattoos",
	TokenPasswords:          "token_passwords",
	Tokens:                  "tokens",
	Users:                   "users",
	Views:                   "views",
}
