// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("AccessToSessionUsingIDSessionSession", testAccessToOneSessionUsingIDSessionSession)
	t.Run("AppointmentToUserUsingIDUserUser", testAppointmentToOneUserUsingIDUserUser)
	t.Run("AppointmentToUserUsingIDTattooArtistUser", testAppointmentToOneUserUsingIDTattooArtistUser)
	t.Run("AuthToUserUsingIDUserUser", testAuthToOneUserUsingIDUserUser)
	t.Run("FollowToUserUsingIDUserUser", testFollowToOneUserUsingIDUserUser)
	t.Run("FollowToProfileUsingIDProfileProfile", testFollowToOneProfileUsingIDProfileProfile)
	t.Run("LikeToUserUsingIDUserUser", testLikeToOneUserUsingIDUserUser)
	t.Run("LikeToProfileUsingIDProfileProfile", testLikeToOneProfileUsingIDProfileProfile)
	t.Run("LikeToPostUsingIDPostPost", testLikeToOnePostUsingIDPostPost)
	t.Run("PostCategoryToPostUsingIDPostPost", testPostCategoryToOnePostUsingIDPostPost)
	t.Run("PostCategoryToCategoryUsingIDCategoryCategory", testPostCategoryToOneCategoryUsingIDCategoryCategory)
	t.Run("PostImageToPostUsingIDPostPost", testPostImageToOnePostUsingIDPostPost)
	t.Run("PostImageToImageUsingIDImageImage", testPostImageToOneImageUsingIDImageImage)
	t.Run("PostToProfileUsingIDProfileProfile", testPostToOneProfileUsingIDProfileProfile)
	t.Run("ProfileCategoryToProfileUsingIDProfileProfile", testProfileCategoryToOneProfileUsingIDProfileProfile)
	t.Run("ProfileCategoryToCategoryUsingIDCategory", testProfileCategoryToOneCategoryUsingIDCategory)
	t.Run("ProfileToUserUsingIDUserUser", testProfileToOneUserUsingIDUserUser)
	t.Run("ProfileToImageUsingIDAvatarImage", testProfileToOneImageUsingIDAvatarImage)
	t.Run("ReviewToUserUsingIDUserUser", testReviewToOneUserUsingIDUserUser)
	t.Run("ReviewToProfileUsingIDProfileProfile", testReviewToOneProfileUsingIDProfileProfile)
	t.Run("RolesUserToUserUsingIDUserUser", testRolesUserToOneUserUsingIDUserUser)
	t.Run("SessionToAuthUsingIDAuthAuth", testSessionToOneAuthUsingIDAuthAuth)
	t.Run("StudioAdminToStudioUsingIDStudioStudio", testStudioAdminToOneStudioUsingIDStudioStudio)
	t.Run("StudioAdminToUserUsingIDOwnerUser", testStudioAdminToOneUserUsingIDOwnerUser)
	t.Run("StudioTattooArtistToUserUsingIDTattooArtistUser", testStudioTattooArtistToOneUserUsingIDTattooArtistUser)
	t.Run("StudioTattooArtistToStudioUsingIDStudioStudio", testStudioTattooArtistToOneStudioUsingIDStudioStudio)
	t.Run("TattooCategoryToTattooUsingIDTattooTattoo", testTattooCategoryToOneTattooUsingIDTattooTattoo)
	t.Run("TattooCategoryToCategoryUsingIDCategoryCategory", testTattooCategoryToOneCategoryUsingIDCategoryCategory)
	t.Run("TattooToProfileUsingIDProfileProfile", testTattooToOneProfileUsingIDProfileProfile)
	t.Run("TattooToPostUsingIDPostPost", testTattooToOnePostUsingIDPostPost)
	t.Run("TattooToImageUsingIDImageImage", testTattooToOneImageUsingIDImageImage)
	t.Run("TokenPasswordToUserUsingIDUserUser", testTokenPasswordToOneUserUsingIDUserUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {
	t.Run("ImageToPostImageUsingIDImagePostImage", testImageOneToOnePostImageUsingIDImagePostImage)
	t.Run("ImageToProfileUsingIDAvatarProfile", testImageOneToOneProfileUsingIDAvatarProfile)
	t.Run("ImageToTattooUsingIDImageTattoo", testImageOneToOneTattooUsingIDImageTattoo)
	t.Run("UserToAuthUsingIDUserAuth", testUserOneToOneAuthUsingIDUserAuth)
	t.Run("UserToProfileUsingIDUserProfile", testUserOneToOneProfileUsingIDUserProfile)
	t.Run("UserToTokenPasswordUsingIDUserTokenPassword", testUserOneToOneTokenPasswordUsingIDUserTokenPassword)
}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("AuthToIDAuthSessions", testAuthToManyIDAuthSessions)
	t.Run("CategoryToIDCategoryPostCategories", testCategoryToManyIDCategoryPostCategories)
	t.Run("CategoryToIDCategoryProfileCategories", testCategoryToManyIDCategoryProfileCategories)
	t.Run("CategoryToIDCategoryTattooCategories", testCategoryToManyIDCategoryTattooCategories)
	t.Run("PostToIDPostLikes", testPostToManyIDPostLikes)
	t.Run("PostToIDPostPostCategories", testPostToManyIDPostPostCategories)
	t.Run("PostToIDPostPostImages", testPostToManyIDPostPostImages)
	t.Run("PostToIDPostTattoos", testPostToManyIDPostTattoos)
	t.Run("ProfileToIDProfileFollows", testProfileToManyIDProfileFollows)
	t.Run("ProfileToIDProfileLikes", testProfileToManyIDProfileLikes)
	t.Run("ProfileToIDProfilePosts", testProfileToManyIDProfilePosts)
	t.Run("ProfileToIDProfileProfileCategories", testProfileToManyIDProfileProfileCategories)
	t.Run("ProfileToIDProfileReviews", testProfileToManyIDProfileReviews)
	t.Run("ProfileToIDProfileTattoos", testProfileToManyIDProfileTattoos)
	t.Run("SessionToIDSessionAccesses", testSessionToManyIDSessionAccesses)
	t.Run("StudioToIDStudioStudioAdmins", testStudioToManyIDStudioStudioAdmins)
	t.Run("StudioToIDStudioStudioTattooArtists", testStudioToManyIDStudioStudioTattooArtists)
	t.Run("TattooToIDTattooTattooCategories", testTattooToManyIDTattooTattooCategories)
	t.Run("UserToIDUserAppointments", testUserToManyIDUserAppointments)
	t.Run("UserToIDTattooArtistAppointments", testUserToManyIDTattooArtistAppointments)
	t.Run("UserToIDUserFollows", testUserToManyIDUserFollows)
	t.Run("UserToIDUserLikes", testUserToManyIDUserLikes)
	t.Run("UserToIDUserReviews", testUserToManyIDUserReviews)
	t.Run("UserToIDUserRolesUsers", testUserToManyIDUserRolesUsers)
	t.Run("UserToIDOwnerStudioAdmins", testUserToManyIDOwnerStudioAdmins)
	t.Run("UserToIDTattooArtistStudioTattooArtists", testUserToManyIDTattooArtistStudioTattooArtists)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("AccessToSessionUsingIDSessionAccesses", testAccessToOneSetOpSessionUsingIDSessionSession)
	t.Run("AppointmentToUserUsingIDUserAppointments", testAppointmentToOneSetOpUserUsingIDUserUser)
	t.Run("AppointmentToUserUsingIDTattooArtistAppointments", testAppointmentToOneSetOpUserUsingIDTattooArtistUser)
	t.Run("AuthToUserUsingIDUserAuth", testAuthToOneSetOpUserUsingIDUserUser)
	t.Run("FollowToUserUsingIDUserFollows", testFollowToOneSetOpUserUsingIDUserUser)
	t.Run("FollowToProfileUsingIDProfileFollows", testFollowToOneSetOpProfileUsingIDProfileProfile)
	t.Run("LikeToUserUsingIDUserLikes", testLikeToOneSetOpUserUsingIDUserUser)
	t.Run("LikeToProfileUsingIDProfileLikes", testLikeToOneSetOpProfileUsingIDProfileProfile)
	t.Run("LikeToPostUsingIDPostLikes", testLikeToOneSetOpPostUsingIDPostPost)
	t.Run("PostCategoryToPostUsingIDPostPostCategories", testPostCategoryToOneSetOpPostUsingIDPostPost)
	t.Run("PostCategoryToCategoryUsingIDCategoryPostCategories", testPostCategoryToOneSetOpCategoryUsingIDCategoryCategory)
	t.Run("PostImageToPostUsingIDPostPostImages", testPostImageToOneSetOpPostUsingIDPostPost)
	t.Run("PostImageToImageUsingIDImagePostImage", testPostImageToOneSetOpImageUsingIDImageImage)
	t.Run("PostToProfileUsingIDProfilePosts", testPostToOneSetOpProfileUsingIDProfileProfile)
	t.Run("ProfileCategoryToProfileUsingIDProfileProfileCategories", testProfileCategoryToOneSetOpProfileUsingIDProfileProfile)
	t.Run("ProfileCategoryToCategoryUsingIDCategoryProfileCategories", testProfileCategoryToOneSetOpCategoryUsingIDCategory)
	t.Run("ProfileToUserUsingIDUserProfile", testProfileToOneSetOpUserUsingIDUserUser)
	t.Run("ProfileToImageUsingIDAvatarProfile", testProfileToOneSetOpImageUsingIDAvatarImage)
	t.Run("ReviewToUserUsingIDUserReviews", testReviewToOneSetOpUserUsingIDUserUser)
	t.Run("ReviewToProfileUsingIDProfileReviews", testReviewToOneSetOpProfileUsingIDProfileProfile)
	t.Run("RolesUserToUserUsingIDUserRolesUsers", testRolesUserToOneSetOpUserUsingIDUserUser)
	t.Run("SessionToAuthUsingIDAuthSessions", testSessionToOneSetOpAuthUsingIDAuthAuth)
	t.Run("StudioAdminToStudioUsingIDStudioStudioAdmins", testStudioAdminToOneSetOpStudioUsingIDStudioStudio)
	t.Run("StudioAdminToUserUsingIDOwnerStudioAdmins", testStudioAdminToOneSetOpUserUsingIDOwnerUser)
	t.Run("StudioTattooArtistToUserUsingIDTattooArtistStudioTattooArtists", testStudioTattooArtistToOneSetOpUserUsingIDTattooArtistUser)
	t.Run("StudioTattooArtistToStudioUsingIDStudioStudioTattooArtists", testStudioTattooArtistToOneSetOpStudioUsingIDStudioStudio)
	t.Run("TattooCategoryToTattooUsingIDTattooTattooCategories", testTattooCategoryToOneSetOpTattooUsingIDTattooTattoo)
	t.Run("TattooCategoryToCategoryUsingIDCategoryTattooCategories", testTattooCategoryToOneSetOpCategoryUsingIDCategoryCategory)
	t.Run("TattooToProfileUsingIDProfileTattoos", testTattooToOneSetOpProfileUsingIDProfileProfile)
	t.Run("TattooToPostUsingIDPostTattoos", testTattooToOneSetOpPostUsingIDPostPost)
	t.Run("TattooToImageUsingIDImageTattoo", testTattooToOneSetOpImageUsingIDImageImage)
	t.Run("TokenPasswordToUserUsingIDUserTokenPassword", testTokenPasswordToOneSetOpUserUsingIDUserUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("ProfileToImageUsingIDAvatarProfile", testProfileToOneRemoveOpImageUsingIDAvatarImage)
	t.Run("TattooToPostUsingIDPostTattoos", testTattooToOneRemoveOpPostUsingIDPostPost)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {
	t.Run("ImageToPostImageUsingIDImagePostImage", testImageOneToOneSetOpPostImageUsingIDImagePostImage)
	t.Run("ImageToProfileUsingIDAvatarProfile", testImageOneToOneSetOpProfileUsingIDAvatarProfile)
	t.Run("ImageToTattooUsingIDImageTattoo", testImageOneToOneSetOpTattooUsingIDImageTattoo)
	t.Run("UserToAuthUsingIDUserAuth", testUserOneToOneSetOpAuthUsingIDUserAuth)
	t.Run("UserToProfileUsingIDUserProfile", testUserOneToOneSetOpProfileUsingIDUserProfile)
	t.Run("UserToTokenPasswordUsingIDUserTokenPassword", testUserOneToOneSetOpTokenPasswordUsingIDUserTokenPassword)
}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {
	t.Run("ImageToProfileUsingIDAvatarProfile", testImageOneToOneRemoveOpProfileUsingIDAvatarProfile)
}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("AuthToIDAuthSessions", testAuthToManyAddOpIDAuthSessions)
	t.Run("CategoryToIDCategoryPostCategories", testCategoryToManyAddOpIDCategoryPostCategories)
	t.Run("CategoryToIDCategoryProfileCategories", testCategoryToManyAddOpIDCategoryProfileCategories)
	t.Run("CategoryToIDCategoryTattooCategories", testCategoryToManyAddOpIDCategoryTattooCategories)
	t.Run("PostToIDPostLikes", testPostToManyAddOpIDPostLikes)
	t.Run("PostToIDPostPostCategories", testPostToManyAddOpIDPostPostCategories)
	t.Run("PostToIDPostPostImages", testPostToManyAddOpIDPostPostImages)
	t.Run("PostToIDPostTattoos", testPostToManyAddOpIDPostTattoos)
	t.Run("ProfileToIDProfileFollows", testProfileToManyAddOpIDProfileFollows)
	t.Run("ProfileToIDProfileLikes", testProfileToManyAddOpIDProfileLikes)
	t.Run("ProfileToIDProfilePosts", testProfileToManyAddOpIDProfilePosts)
	t.Run("ProfileToIDProfileProfileCategories", testProfileToManyAddOpIDProfileProfileCategories)
	t.Run("ProfileToIDProfileReviews", testProfileToManyAddOpIDProfileReviews)
	t.Run("ProfileToIDProfileTattoos", testProfileToManyAddOpIDProfileTattoos)
	t.Run("SessionToIDSessionAccesses", testSessionToManyAddOpIDSessionAccesses)
	t.Run("StudioToIDStudioStudioAdmins", testStudioToManyAddOpIDStudioStudioAdmins)
	t.Run("StudioToIDStudioStudioTattooArtists", testStudioToManyAddOpIDStudioStudioTattooArtists)
	t.Run("TattooToIDTattooTattooCategories", testTattooToManyAddOpIDTattooTattooCategories)
	t.Run("UserToIDUserAppointments", testUserToManyAddOpIDUserAppointments)
	t.Run("UserToIDTattooArtistAppointments", testUserToManyAddOpIDTattooArtistAppointments)
	t.Run("UserToIDUserFollows", testUserToManyAddOpIDUserFollows)
	t.Run("UserToIDUserLikes", testUserToManyAddOpIDUserLikes)
	t.Run("UserToIDUserReviews", testUserToManyAddOpIDUserReviews)
	t.Run("UserToIDUserRolesUsers", testUserToManyAddOpIDUserRolesUsers)
	t.Run("UserToIDOwnerStudioAdmins", testUserToManyAddOpIDOwnerStudioAdmins)
	t.Run("UserToIDTattooArtistStudioTattooArtists", testUserToManyAddOpIDTattooArtistStudioTattooArtists)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("PostToIDPostTattoos", testPostToManySetOpIDPostTattoos)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("PostToIDPostTattoos", testPostToManyRemoveOpIDPostTattoos)
}
