// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testStudios(t *testing.T) {
	t.Parallel()

	query := Studios()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testStudiosDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Studios().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStudiosQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Studios().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Studios().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStudiosSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StudioSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Studios().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testStudiosExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := StudioExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Studio exists: %s", err)
	}
	if !e {
		t.Errorf("Expected StudioExists to return true, but got false.")
	}
}

func testStudiosFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	studioFound, err := FindStudio(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if studioFound == nil {
		t.Error("want a record, got nil")
	}
}

func testStudiosBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Studios().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testStudiosOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Studios().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testStudiosAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	studioOne := &Studio{}
	studioTwo := &Studio{}
	if err = randomize.Struct(seed, studioOne, studioDBTypes, false, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}
	if err = randomize.Struct(seed, studioTwo, studioDBTypes, false, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = studioOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = studioTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Studios().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testStudiosCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	studioOne := &Studio{}
	studioTwo := &Studio{}
	if err = randomize.Struct(seed, studioOne, studioDBTypes, false, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}
	if err = randomize.Struct(seed, studioTwo, studioDBTypes, false, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = studioOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = studioTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Studios().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func studioBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Studio) error {
	*o = Studio{}
	return nil
}

func studioAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Studio) error {
	*o = Studio{}
	return nil
}

func studioAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Studio) error {
	*o = Studio{}
	return nil
}

func studioBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Studio) error {
	*o = Studio{}
	return nil
}

func studioAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Studio) error {
	*o = Studio{}
	return nil
}

func studioBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Studio) error {
	*o = Studio{}
	return nil
}

func studioAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Studio) error {
	*o = Studio{}
	return nil
}

func studioBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Studio) error {
	*o = Studio{}
	return nil
}

func studioAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Studio) error {
	*o = Studio{}
	return nil
}

func testStudiosHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Studio{}
	o := &Studio{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, studioDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Studio object: %s", err)
	}

	AddStudioHook(boil.BeforeInsertHook, studioBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	studioBeforeInsertHooks = []StudioHook{}

	AddStudioHook(boil.AfterInsertHook, studioAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	studioAfterInsertHooks = []StudioHook{}

	AddStudioHook(boil.AfterSelectHook, studioAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	studioAfterSelectHooks = []StudioHook{}

	AddStudioHook(boil.BeforeUpdateHook, studioBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	studioBeforeUpdateHooks = []StudioHook{}

	AddStudioHook(boil.AfterUpdateHook, studioAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	studioAfterUpdateHooks = []StudioHook{}

	AddStudioHook(boil.BeforeDeleteHook, studioBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	studioBeforeDeleteHooks = []StudioHook{}

	AddStudioHook(boil.AfterDeleteHook, studioAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	studioAfterDeleteHooks = []StudioHook{}

	AddStudioHook(boil.BeforeUpsertHook, studioBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	studioBeforeUpsertHooks = []StudioHook{}

	AddStudioHook(boil.AfterUpsertHook, studioAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	studioAfterUpsertHooks = []StudioHook{}
}

func testStudiosInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Studios().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStudiosInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(studioColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Studios().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testStudioToManyIDStudioStudioAdmins(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Studio
	var b, c StudioAdmin

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, studioAdminDBTypes, false, studioAdminColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, studioAdminDBTypes, false, studioAdminColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.IDStudio = a.ID
	c.IDStudio = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.IDStudioStudioAdmins().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.IDStudio == b.IDStudio {
			bFound = true
		}
		if v.IDStudio == c.IDStudio {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := StudioSlice{&a}
	if err = a.L.LoadIDStudioStudioAdmins(ctx, tx, false, (*[]*Studio)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.IDStudioStudioAdmins); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.IDStudioStudioAdmins = nil
	if err = a.L.LoadIDStudioStudioAdmins(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.IDStudioStudioAdmins); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testStudioToManyIDStudioStudioTattooArtists(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Studio
	var b, c StudioTattooArtist

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, studioTattooArtistDBTypes, false, studioTattooArtistColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, studioTattooArtistDBTypes, false, studioTattooArtistColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.IDStudio = a.ID
	c.IDStudio = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.IDStudioStudioTattooArtists().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.IDStudio == b.IDStudio {
			bFound = true
		}
		if v.IDStudio == c.IDStudio {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := StudioSlice{&a}
	if err = a.L.LoadIDStudioStudioTattooArtists(ctx, tx, false, (*[]*Studio)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.IDStudioStudioTattooArtists); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.IDStudioStudioTattooArtists = nil
	if err = a.L.LoadIDStudioStudioTattooArtists(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.IDStudioStudioTattooArtists); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testStudioToManyAddOpIDStudioStudioAdmins(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Studio
	var b, c, d, e StudioAdmin

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, studioDBTypes, false, strmangle.SetComplement(studioPrimaryKeyColumns, studioColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*StudioAdmin{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, studioAdminDBTypes, false, strmangle.SetComplement(studioAdminPrimaryKeyColumns, studioAdminColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*StudioAdmin{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddIDStudioStudioAdmins(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.IDStudio {
			t.Error("foreign key was wrong value", a.ID, first.IDStudio)
		}
		if a.ID != second.IDStudio {
			t.Error("foreign key was wrong value", a.ID, second.IDStudio)
		}

		if first.R.IDStudioStudio != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.IDStudioStudio != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.IDStudioStudioAdmins[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.IDStudioStudioAdmins[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.IDStudioStudioAdmins().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testStudioToManyAddOpIDStudioStudioTattooArtists(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Studio
	var b, c, d, e StudioTattooArtist

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, studioDBTypes, false, strmangle.SetComplement(studioPrimaryKeyColumns, studioColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*StudioTattooArtist{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, studioTattooArtistDBTypes, false, strmangle.SetComplement(studioTattooArtistPrimaryKeyColumns, studioTattooArtistColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*StudioTattooArtist{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddIDStudioStudioTattooArtists(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.IDStudio {
			t.Error("foreign key was wrong value", a.ID, first.IDStudio)
		}
		if a.ID != second.IDStudio {
			t.Error("foreign key was wrong value", a.ID, second.IDStudio)
		}

		if first.R.IDStudioStudio != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.IDStudioStudio != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.IDStudioStudioTattooArtists[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.IDStudioStudioTattooArtists[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.IDStudioStudioTattooArtists().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testStudiosReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStudiosReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := StudioSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testStudiosSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Studios().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	studioDBTypes = map[string]string{`ID`: `bigint`, `Description`: `text`, `Direction`: `jsonb`, `Email`: `text`, `Phone`: `text`, `CreatedAt`: `timestamp without time zone`}
	_             = bytes.MinRead
)

func testStudiosUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(studioPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(studioAllColumns) == len(studioPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Studios().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, studioDBTypes, true, studioPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testStudiosSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(studioAllColumns) == len(studioPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Studio{}
	if err = randomize.Struct(seed, o, studioDBTypes, true, studioColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Studios().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, studioDBTypes, true, studioPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(studioAllColumns, studioPrimaryKeyColumns) {
		fields = studioAllColumns
	} else {
		fields = strmangle.SetComplement(
			studioAllColumns,
			studioPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := StudioSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testStudiosUpsert(t *testing.T) {
	t.Parallel()

	if len(studioAllColumns) == len(studioPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Studio{}
	if err = randomize.Struct(seed, &o, studioDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Studio: %s", err)
	}

	count, err := Studios().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, studioDBTypes, false, studioPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Studio struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Studio: %s", err)
	}

	count, err = Studios().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
